### ISSUE TITLE
Add README files 📃 

### ISSUE THREAD

**Issue by Umesh-01** [sirilalithaadapa/Python-Projects#3]
I think there must be a **README.md** file for each project in your sub-directories. 🙂 

Let's take an example of [**Weather**](https://github.com/sirilalithaadapa/Python-Projects/tree/master/Weather) project 🌦️ in your repository 📂 
It should contain these things or more in **README.md** file--
+ a short description 📄  
+ what modules are used 📜 
+ which method is used to fetch data like API or Web Scraping, etc. 🤖 
+ and probably the output 💻

**Comment by sirilalithaadapa** [comment]
yeah ! okay i will work on it and add the README.md in sub-directories too
